### ISSUE TITLE
Api2Pdf\Exception\ConversionException: Exit with code 1 due to network error: HostNotFoundError

### ISSUE THREAD

**Issue by ikev61** [Api2Pdf/api2pdf.php#13]
I made a request and got this error. Any fix?
Api2Pdf\Exception\ConversionException: Exit with code 1 due to network error: HostNotFoundError

**Comment by apexdodge** [comment]
@ikev61 

There must be some bug in your code. This error typically happens when you try to generate PDF but are missing a fully resolved url - make sure all urls have fully resolved urls. Article: https://www.api2pdf.com/solved-contentnotfounderror-wkhtmltopdf-exited-with-code-1/

If you can't solve it, then you should do testing directly against the REST API by following this tutorial:
https://www.api2pdf.com/how-to-use-api2pdfs-swaggerhub-to-get-the-most-out-of-our-support-team/
