### ISSUE TITLE
Add an interface for the public methods

### ISSUE THREAD

**Issue by smoelker** [Api2Pdf/api2pdf.php#8]
The Api2Pdf class has no interface and is therefore it's difficult to unit tests classes that take a dependency on that class.

Additionally the filename, inline and options properties should not be class members but method variables since they usually vary per call and, more importantly, it makes the class stateful which is undesirable when using a shared instance (in a DI container for example).

**Comment by apexdodge** [comment]
@smoelker I agree about adding the interface, I think that's a sound idea.

Regarding how the advanced options are set (inline, filename, advanced options), I had mixed feelings about that when #5 pull request came in, as I see your point, but ultimately I accepted PR.

I believe in our first version of the PHP code we made use of optional arguments the same way we do it with our python library: https://github.com/Api2Pdf/api2pdf.python, but PHP's optional arguments functionality is poorly implemented my opinion. For example, in python I can call (html, file_name="test.pdf") or (html, inline=True). Both will work as expected. But with PHP, you cannot do that (see this: https://stackoverflow.com/questions/13007155/multiple-optional-argument-in-a-function)

As a result, I was getting a number of support requests from developers who were easily making mistakes with regards to the optional arguments. When I saw #5, I was OK with it due to the explicit nature of specifying the advanced properties, and have not received support requests on that usage since. So while in theory I agree with this, in practice, most developers fall short in their competency and we have to take that into consideration. Of course feel free to fork.

Thank you for your thoughts.

**Comment by smoelker** [comment]
That's really sas to hear but I completely understand from your perspective.

What are your thoughts on making all the options typed and combining the standard options and the advanced options? So every method that accepts options would have an url/html argument and typed options argument like this: 

```php
$options = (new HeadlessChromeOptions())
->setInline()
->setFilename('test.pdf')
->setLandscape()
->etc..... ;

$client->headlessChromeFromUrl($url, $options);
```

Additionally we could add type hints to make it an even better experience but would break php5 compatibility.

**Comment by apexdodge** [comment]
rewrote the library for our v2 launch. 

Can preview it here: https://github.com/Api2Pdf/api2pdf.php/tree/2.0.0
